{% set name = "boule" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fde5908b8a88f0f05ccbf23f2aa422b9d81a2a3e6ed6c1ce65afda0bb6254717

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=45
    - setuptools_scm >=6.2
  run:
    - python >=3.8
    - numpy >=1.19
    - attrs >=19.3.0
    - scipy >=1.8.0

test:
  imports:
    - boule

about:
  home: https://github.com/fatiando/boule
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Reference ellipsoids for geodesy and geophysics
  description: |
    Boule is Python library for representing Reference Ellipsoids, calculating
    their gravity fields, and converting coordinates defined on the ellipsoids.
    The main use cases are 1) calculating normal gravity (for gravity anomalies
    and disturbances); 2) spherical gravity modeling, which requires geodetic
    to geocentric spherical coordinate conversions; 3) input ellipsoid
    parameters for spherical harmonic analysis. Boule is French for ball and
    also a traditional shape of bread resembling a squashed ball (much like the
    Earth).
  doc_url: https://www.fatiando.org/boule/
  dev_url: https://github.com/fatiando/boule

extra:
  recipe-maintainers:
    - leouieda
    - santisoler
